sudo: required

language: python

services:
  - docker

script:
  - python -m pytest -v

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_TAG
  - docker build -t $TRAVIS_REPO_SLUG .
  - docker push $TRAVIS_REPO_SLUG